# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Place here your production web-root
ORIGIN: http://localhost:8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"
  - "android >= 4.4"
